# Generated by Django 5.2.1 on 2025-05-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('eventType', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('eventYear', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('eventDate', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('eventLocation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
