# Generated by Django 5.2.1 on 2025-05-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventSpeakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventSpeakerName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('eventSpeakerCompany', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('eventSpeakerDescription', models.TextField(blank=True, null=True)),
                ('viewSpeakerButtonLabel', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('speakerProfilePageLink', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('eventSpeakerHomePageImage', models.TextField(blank=True, null=True)),
                ('eventSpeakerProfilePageImage', models.TextField(blank=True, null=True)),
                ('eventSpeakerAgendaPageImage', models.TextField(blank=True, null=True)),
                ('eventSpeakerEmail', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('eventSpeakerProposedTitle', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('isParticipated', models.CharField(default='No', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
