# Generated by Django 5.2.1 on 2025-06-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_delegatesaddons_deligatepackageinclusionpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspeakers',
            name='eventSpeakerProfilePageDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
