# Generated by Django 5.2.3 on 2025-06-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_eventspeakers_eventspeakerprofilepagedescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsorOfferCouponHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
                ('offerCouponId', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.offercoupon')),
                ('relatedSponsorCompanyId', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.sponseredcompanydetails')),
            ],
        ),
    ]
