# Generated by Django 5.2.3 on 2025-07-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_sponsoroffercouponhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspeakers',
            name='eventSpeakerShortDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
