# Generated by Django 5.2.3 on 2025-07-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_eventspeakers_eventspeakershortdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventspeakers',
            old_name='eventSpeakerAgendaPageImage',
            new_name='eventSpeakerFeaturedPageImage',
        ),
    ]
