# Generated by Django 5.2.3 on 2025-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_rename_eventspeakeragendapageimage_eventspeakers_eventspeakerfeaturedpageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsponsors',
            name='sponsorWebsite',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
