# Generated by Django 5.2.3 on 2025-07-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_eventsponsors_sponsorwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpastattandees',
            name='pastAttandeeLogo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
