# Generated by Django 5.2.3 on 2025-08-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0009_eventpastattandees_pastattandeelogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorpackageinclusions',
            name='sponsorBenifitId',
        ),
        migrations.RemoveField(
            model_name='sponsorpackageinclusions',
            name='sponsorPackageTypeId',
        ),
        migrations.AddField(
            model_name='sponsorpackagetypes',
            name='delegatePassQty',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sponsorpackagetypes',
            name='exhibitSpace',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sponsorpackagetypes',
            name='inviteDiscount',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sponsorpackagetypes',
            name='sponsorPackageShowOrder',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='sponsorBenefits',
        ),
        migrations.DeleteModel(
            name='sponsorPackageInclusions',
        ),
    ]
