# Generated by Django 5.2.3 on 2025-08-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0010_remove_sponsorpackageinclusions_sponsorbenifitid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventLeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('leaderLogo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
