# Generated by Django 5.2.3 on 2025-09-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0011_eventleaders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventagenda',
            name='dayName',
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='sectionLabel',
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='sectionLeftKeys',
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='sectionLeftLogo',
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='sectionName',
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='sectionRightBullets',
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='sponsoredBy',
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='Speaker1AgendaImg',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='Speaker1CompanyImg',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='Speaker1Id',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='Speaker2AgendaImg',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='Speaker2CompanyImg',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='Speaker2Id',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='bulletPoints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='day',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='heading',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='industryTrends',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='panelModerators',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='panelSpeakerIds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='panelSpeakerImages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='selectedSpeakers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='singleSpeakerAgendaImg',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='singleSpeakerCompanyImg',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='singleSpeakerId',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='sortOrder',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='speaker1Bullets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='speaker2Bullets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='speakerFormat',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='sponsorBy',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='status',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
