# Generated by Django 5.2.3 on 2025-09-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0012_remove_eventagenda_dayname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgeneralsettings',
            name='currencySymbol',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
