# Generated by Django 5.2.3 on 2025-10-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0013_eventgeneralsettings_currencysymbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='eventShortCode',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
