# Generated by Django 5.2.3 on 2025-10-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0014_eventdetails_eventshortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventagenda',
            name='sortOrder',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
