# Generated by Django 5.2.3 on 2025-10-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0015_alter_eventagenda_sortorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorcompanytransectiondata',
            name='additionalDelegateAmoount',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
