# Generated by Django 5.2.3 on 2025-12-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0016_sponsorcompanytransectiondata_additionaldelegateamoount'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='isSeoEnable',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventspeakers',
            name='eventSpeakerMetaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventspeakers',
            name='eventSpeakerMetaTitle',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsponsors',
            name='eventSponsorMetaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsponsors',
            name='eventSponsorMetaTitle',
            field=models.CharField(blank=True, null=True),
        ),
    ]
