services:
  - type: web
    name: admin-panel-bitcoin-seo
    runtime: static
    buildCommand: cd AdminPanel && npm install --legacy-peer-deps && npm run build
    staticPublishPath: AdminPanel/build
    envVars:
      - key: NODE_OPTIONS
        value: --max_old_space_size=4096
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
