# Generated by Django 5.2.1 on 2025-05-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homePageNavMainCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navMainCategoryName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('navMainCategoryPath', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='homePageNavSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navSubCategoryName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('navSubCategoryPath', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
                ('navMainCategoryId', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Myadmin.homepagenavmaincategories')),
            ],
        ),
    ]
