# Generated by Django 5.2.1 on 2025-05-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0002_homepagenavmaincategories_homepagenavsubcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='homePageVideoSectionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoLink', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('eventDetailBackImage', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='videoSectionUserOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoSectionUserOptionName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('videoSectionUserOptionShortDescription', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('videoSectionUserOptionOrderNo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('videoSectionUserOptionArrowIcon', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
