# Generated by Django 5.2.1 on 2025-05-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0003_homepagevideosectioninput_videosectionuseroptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='speakerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speakerSectionFirstTitle', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('speakerSectionSecondTitle', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('speakerSectionButtonTitle', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('speakerSectionButtonIcon', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='videosectionuseroptions',
            name='videoSectionUserOptionRedirectRoute',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
