# Generated by Django 5.2.1 on 2025-06-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0005_companieslogosection_contactusdata_contactushelpdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorpagedata',
            name='introParaImage',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
