# Generated by Django 5.2.3 on 2025-07-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0006_sponsorpagedata_introparaimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuepagedata',
            name='venueAddressLink',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='venuepagedata',
            name='venueMapLink',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
