# Generated by Django 5.2.3 on 2025-08-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0007_venuepagedata_venueaddresslink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnewspoint',
            name='newsShortDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
