# Generated by Django 5.2.3 on 2025-08-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0008_generalnewspoint_newsshortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnewspoint',
            name='isTopNews',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
