# Generated by Django 5.2.3 on 2025-08-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0009_generalnewspoint_istopnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='mediaPageHelpers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyPersonName', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('companyPersonEmail', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('companyPersonPhone', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
