# Generated by Django 5.2.3 on 2025-08-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0010_mediapagehelpers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuepagedata',
            name='venueAddressLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuepagedata',
            name='venueContact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuepagedata',
            name='venueLocation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuepagedata',
            name='venueMapLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
