# Generated by Django 5.2.3 on 2025-08-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0011_alter_venuepagedata_venueaddresslink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='standOutCrowdRequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesterName', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('requesterCompanyName', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('requesterMobile', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('requesterEmail', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('requesterMessage', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
