# Generated by Django 5.2.3 on 2025-08-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0014_quickproposalrequestdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='endUserPassRegistrationRequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('userCompany', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('userEmail', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('userMobile', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('userInterest', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('noOfAttandees', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('userMessage', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
