# Generated by Django 5.2.3 on 2025-09-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0016_pastattandeehomedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagevideosectioninput',
            name='videoLink',
        ),
        migrations.AddField(
            model_name='homepagevideosectioninput',
            name='videoLinkmp4',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepagevideosectioninput',
            name='videoLinkwebm',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
