# Generated by Django 5.2.3 on 2025-09-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0017_remove_homepagevideosectioninput_videolink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagevideosectioninput',
            name='eventExpertSpeakerBackImage',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepagevideosectioninput',
            name='eventStataticsBackImage',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
