# Generated by Django 5.2.3 on 2025-09-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0018_homepagevideosectioninput_eventexpertspeakerbackimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagevideosectioninput',
            name='videoReplaceImage',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
