# Generated by Django 5.2.3 on 2025-09-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0019_homepagevideosectioninput_videoreplaceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersocialmediaoptions',
            name='platformIcon',
        ),
        migrations.RemoveField(
            model_name='footersocialmediaoptions',
            name='platformName',
        ),
        migrations.RemoveField(
            model_name='footersocialmediaoptions',
            name='platformProfileLink',
        ),
        migrations.AddField(
            model_name='footersocialmediaoptions',
            name='emailLink',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='footersocialmediaoptions',
            name='facebookLink',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='footersocialmediaoptions',
            name='instagramLink',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='footersocialmediaoptions',
            name='linkedinLink',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='footersocialmediaoptions',
            name='twitterLink',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
