# Generated by Django 5.2.3 on 2025-12-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0020_remove_footersocialmediaoptions_platformicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnewspoint',
            name='newsImageAltText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalnewspoint',
            name='newsMetaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalnewspoint',
            name='newsMetaTitle',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
